services:
  backend:
    image: ghcr.io/panik10/java-react-sample-app-cicd-demo-be:latest
    pull_policy: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: ghcr.io/panik10/java-react-sample-app-cicd-demo-fe:latest
    pull_policy: always
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_DESCOPE_PROJECT_ID=P3CoHQVvalPao3I3FVTDFu6HSYSL

networks:
  app-network:
    driver: bridge