name: build

on: 
  workflow_dispatch:

jobs:

  lint-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      # version setup node 6.4.0 can be used, as it has node 24 and cache on for npm by default, but for demonstration reasons I will use 4.4.0
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Lint FrontEnd
        run: npm ci && npm run lint
        working-directory: client
      - name: Test FrontEnd
        run: npm test
        working-directory: client

  lint-test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: actions/setup-java@v4.8.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Lint and Test Backend
        run: ./mvnw verify
        working-directory: server
        continue-on-error: true

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0

